api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin