# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
#security:
#
#    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
#    providers:
#        in_memory:
#            memory: ~
#
#    firewalls:
#        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        main:
#            anonymous: ~
#            # activate different ways to authenticate
#
#            # http_basic: ~
#            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
#
#            # form_login: ~
#            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
security:
    encoders:
        ApiBundle\Entity\User:
            algorithm: bcrypt
    providers:
        our_db_provider:
            entity:
                class: ApiBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        main:
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider